In [1]:
#Code Snak 01.28.2025
#1. create two 10x10 arrays of zeros named fleet and find.
#2. In fleet 

In [40]:
import numpy as np
import random

fleet = np.zeros((10,10), dtype=int)
fleet[4, 3:8] = 1
fleet[6:9, 6] = 2

#hits
fleet[4,3] *= -1
fleet[4,4] *= -1
fleet[4,5] *= -1
fleet[4,6] *= -1
print(fleet)
print()


find = np.zeros((10,10), dtype=int)
#marks
find[0,0] = -1
find[5,4] = -1
find[9,9] = -1
find[0,9] = -1
find[3,2] = -1
find[7,7] = -1
find[8,8] = -1
print(find)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1 -1 -1  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]

[[-1  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  0  0 -1]]
