# CS233 Homework 1 (total points: 100)

- Run all code cells so that every block shows its output before exporting.
- Export as HTML (.html) and submit that file.
- To get all points for each question, you need to include the output of your code AND your explanation.

## Question 1 (output 5 points, explanation 5 points, 10 points in total): 

Create a 1D NumPy array containing the integers from 0 to 9 (inclusive). Print the array and its `dtype`.

In [15]:
import numpy as np

numbers = np.array(range(10))

print(numbers, numbers.dtype)

[0 1 2 3 4 5 6 7 8 9] int64


Your explanation:
First we assign the variable numbers using numpy's array class and give it a range of 10 as to include the numbers between 0 and 9.

This array is a one dimensional (flat) array given that we have no second row.

Numpy by default will try to assign a default dtype which in this case are 64 bit integers.

Finally we print both the array itself and its dtype by calling it's ndarray object property.

## Question 2 (output 5 points, explanation 5 points, 10 points in total): 

Given a 1D array `a = np.array([3, 6, 9, 12, 15])`, compute (a) the elementwise square of `a` and (b) the sum of all elements. Show both results. Noted that you must sove the problem of using array-oriented programming (no for loop allowed).

In [26]:
import numpy as np

a = np.array([3, 6, 9, 12, 15])
squared = np.square(a)
total = np.sum(a)



print(f"squared : {squared}\nsum : {total}")
# TODO: compute the elementwise square and the total sum
# squared = ???
# total = ???
# print("squared:", squared)
# print("sum:", total)

squared : [  9  36  81 144 225]
sum : 45


Your explanation:

We define two variables `squared` and `total` then using numpy functions `numpy.square` and `numpy.sum()` we find the elementwise square of a and the sum of a.

The output is using an f-string to print both variables.


## Question 3 (output 5 points, explanation 5 points, 10 points in total): 

Construct a 2x3 array filled with zeros and then replace the last column with ones using slicing (without loops). Display the final array.

In [37]:
import numpy as np

matrix = np.zeros((2, 3))

#test cases:
#matrix = np.zeros((4, 4))
#matrix = np.zeros((5, 7))

matrix[: , -1:] = 1

print(matrix)

[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]]


Your explanation:

We first specify that we want to modify every row of the matrix by using ` : `, then we use ` -1: ` to indicate that we want to modify the last element of each row. We then assign that value as 1. Something to note is that this solution allows the matrix to be any size.


## Question 4 (output 5 points, explanation 5 points, 10 points in total): 

Let `b = np.arange(12).reshape(3, 4)`.

1.	Extract the second row of b.

2.	Extract the fourth column of b.

3.	Compute the mean of all elements in b.

In [51]:
import numpy as np

b = np.arange(12).reshape(3, 4)

print(b) #for refrence

# second row
row2 = b[1]

# fourth column
col4 = b[:, 3:]

# mean of all elements
mean_val = b.mean()

print("Second row:", row2)
print("Fourth column:", col4)
print("Mean of all elements:", mean_val)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Second row: [4 5 6 7]
Fourth column: [[ 3]
 [ 7]
 [11]]
Mean of all elements: 5.5


Your explanation:

Selecting row 2 uses a slice value of 1 because python counts with a zero index meaning that our first element `[0, 1, 2, 3]` in python's eyes is zero and our second element `[4, 5, 6, 7]` is refrenced as the first. This is like the difference between the first floor in the US versus Europe we call the ground floor the first floor while Europeans would call it zero (or just ground floor).

As for getting the fourth column similar methods seen in question 3 are used. An important distinction is that we are not selecting only the last element like done previously as if the shape of b was differnt the value of the last column and fourth column would not always be the same value.

nparray has a built in function to calculate the mean.

## Question 5 (output 5 points, explanation 5 points, 10 points in total): 

Given a 4x4 array of consecutive integers starting at 10. Use boolean masking to set all elements greater than 20 to zero and print the modified array.

In [ ]:
import numpy as np

array_4_4 = np.arange(10, 26).reshape(4, 4)
# TODO: build the boolean mask and apply it
print(array_4_4)

Your explanation:


## Question 6 (output 5 points, explanation 5 points, 10 points in total): 

You are given a 2D NumPy.

1.Compute the cumulative sum down the columns. Show the output and explain how the numbers are calculated column by column.
    
2.Compute the cumulative sum across each row. Show the output and explain how the numbers are calculated row by row.

In [ ]:
import numpy as np

arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

print("Cumulative sum down columns:")
# YOU CODE HERE; PRINT YOUR RESULTS

print("\nCumulative sum across rows:")
# YOUR CODE HERE; PRINT YOUR RESULTS

Your explanation:


## Question 7 (output 5 points, explanation 5 points, 10 points in total): 

You are given a 5×5 array of random integers between -5 and 5.

1.	Replace even numbers with 1 and odd numbers with -1.

2.	Show the final array.


In [ ]:
import numpy as np

# Create array of random integers from -5 to 5
rng = np.random.default_rng(seed=42)
arr = rng.integers(-5, 6, size=(5, 5))
print("Original array:")
print(arr)

# hint 1: First find even numbers (boolean mask)

# hint 2: Replace even numbers with 1, odd numbers with -1, by using np.where

print("Transformed array:")
print(new_arr)

Your explanation:


## Question 8 (output 5 points, explanation 5 points, 10 points in total): 

Create a 2D NumPy array (4×5) with random numbers generated from a standard normal distribution, then sort it along columns and rows separately.

In [ ]:
import numpy as np

# Your code
# print the array sorted by columns
# print the array sorted by rows

Your explanation:

## Question 9 (20 points in total)

Hint: Read Chapter 4.7 (https://wesmckinney.com/book/numpy-basics#example_random_walks) and understand the random walk problem and complete the following question


a) (5 points) Pure Python Way: Simulate one random walk of 800 steps where each step is either +2 or -2 with equal probability. Plot the walk by using the provided code.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt # pip install matplotlib, if you don't have it installed
import random
position = 0
walk = [position]
# implement the random walk here using a for loop

plt.plot(walk[:])

b) (5 points) Numpy Way: Solve question a) using numpy way, so for-loop is not allowed.

In [ ]:
# your numpy style code here
plt.plot(walk[:])

c) (10 points = 6 points coding + 4 points explanation) use numpy coding style

Simulate one walk 1000 steps each with two different setups:
- Steps of ±1 (equal probability).
- Steps drawn from [-2, -1, 1, 3] with equal probability.

For each case:
- Print both results and explain which case tends to wander farther, and why.

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))

# Example walk with steps ±1
# your code here
# walk1 = #
plt.plot(walk1, label="±1 walk")

# Example walk with steps from [-2,-1,1,3]
# your code here
# walk2 = #
plt.plot(walk2, label="[-2,-1,1,3] walk")

plt.legend()
plt.title("Example random walks")
plt.xlabel("Step")
plt.ylabel("Position")
plt.show()

Your explanation:
- How does your code work?

- In 2 cases above, which case tends to wander farther, and why?